### ISSUE TITLE
Not getting Lighthouse Results

### ISSUE THREAD

**Issue by Yamikamisama** [marcelduran/webpagetest-api#105]
Hey there so I am running this code:

```javascript
const WebPageTest = require('webpagetest');
const wpt = new WebPageTest('www.webpagetest.org', API_KEY);

let opts = {
  url: 'https://google.com/',
  apiKey,
  strategy: 'mobile'
};

exports.helloWorld = function helloWorld(req, res) {
  wpt.runTest(opts.url, {pollResults: 5, timeout: 5000, lighthouse: true}, (err, data) => {
    res.status(200).send(data);
  });
};
```

And it is returning data, however it does not return Lighthouse Data, which is what I primarily need.
![screen shot 2017-12-19 at 2 10 15 pm](https://user-images.githubusercontent.com/8148176/34178137-2208a38a-e4d4-11e7-9cb8-9eed4aa34e2a.png)

Any clue what Im doing wrong?

**Comment by pmeenan** [comment]
Can you open this as an issue in the [webpagetest](https://github.com/WPO-Foundation/webpagetest) project?

What output do you see when you click on the ? for the score?  It should provide a log and an indication of why it failed.

You also REALLY shouldn't be posting your API key for anyone else to take and use.

**Comment by Yamikamisama** [comment]
I opened it there

**Comment by Yamikamisama** [comment]
![screen shot 2017-12-19 at 4 41 42 pm](https://user-images.githubusercontent.com/8148176/34180120-88ebee16-e4db-11e7-875b-c8e5f5331899.png)


And this is what it returns

**Comment by Yamikamisama** [comment]
fixed this by sending it here

`wpt.runTest(opts.url, {location: 'Dulles_MotoG4', pollResults: 5, timeout: 5000, lighthouse: true}, (err, data) => {`
