### ISSUE TITLE
Not returning expected JSON

### ISSUE THREAD

**Issue by Yamikamisama** [marcelduran/webpagetest-api#106]
```javascript
wpt.runTest(opts.url, {
    location: 'Dulles_MotoG4',
    pollResults: 5,
    timeout: 5000,
    lighthouse: true
  }, (err, data) => {
  return data;
});
```

So I have been working on getting data back from the API and everything has been fine until today somehow my requests started returning a completely JSON. It used to return a set of data with key:value pairs with TTFB etc, now it returns the below.

![screen shot 2018-01-02 at 3 19 28 pm](https://user-images.githubusercontent.com/8148176/34498602-65ffa0aa-efd0-11e7-9e0c-18ab4ddf57d9.png)

Was there a change?

**Comment by navinjoy** [comment]
we also started seeing the same issue starting today.

**Comment by vasikarla** [comment]
+1

**Comment by svg7** [comment]
+1

**Comment by pmeenan** [comment]
Still having issues?  There was an issue with the public WebPageTest instance for a couple of hours this morning but it should have been fixed ~3 hours ago.

**Comment by navinjoy** [comment]
Yes I tried an hour back and the issue was there.
This is the wpt id - 180102_QG_0c5e82ff79ddb6381dbb627530490821

**Comment by Yamikamisama** [comment]
@pmeenan Yup still returning the wrong JSON

![screen shot 2018-01-02 at 4 11 36 pm](https://user-images.githubusercontent.com/8148176/34500191-aeefec0a-efd7-11e7-9534-b6148d374a52.png)

If you click the url it will take you to the html page with the info, but i want the JSON of data, which is what used to return.

HTML PAGE: http://www.webpagetest.org/results.php?test=180102_VT_2c0fa35c9a3e47412648de9c4684e588

**Comment by pmeenan** [comment]
Sorry, should be fixed now - fun php equality where 0 == 'lighthouse' resolves to true.

**Comment by Yamikamisama** [comment]
@pmeenan Okay ill test 👍

**Comment by Yamikamisama** [comment]
@pmeenan thanks for putting in the fix 👍  everything came back as expected!

**Comment by svg7** [comment]
thanks @pmeenan
