### ISSUE TITLE
All locations are failing in nodejs

### ISSUE THREAD

**Issue by jdmevo123** [marcelduran/webpagetest-api#135]
Node js wrapper is failing all tests when a location is specified:

example:
```
wpt.runTest('http://marcelduran.com/webpagetest-api', {location: 'Chicago:Chrome'}, (err, data) => {
  console.log(err || data);
});
```
Fails with 'Invalid Location, please try submitting your test request again.'

The only location I can get to work is the default Dulles:Chrome.

**Comment by pmeenan** [comment]
It's not a wrapper problem, the Chicago location went away and is no longer
valid.

**Comment by jdmevo123** [comment]
Thanks @pmeenan , Sorry i should of pulled the latest locations. So pulling with the latest location as an example Texas2:Chrome comes as valid and OK, but running with the wrapper fails with invalid Location.

`wpt.runTest('http://marcelduran.com/webpagetest-api', {location: 'Texas2:Chrome'}, (err, data) => {
  console.log(err || data);
});`

**Comment by pmeenan** [comment]
Most API keys are limited in the locations they can access.  Here are the
locations available through the API:
https://www.webpagetest.org/getLocations.php?k=A&f=html

**Comment by tkadlec** [comment]
Since there hasn't been any more activity on this, I'm going to go ahead and close the issue. @jdmevo123 let us know if Pat's last response didn't solve it for you.
