### ISSUE TITLE
missing API key

### ISSUE THREAD

**Issue by Anenth** [marcelduran/webpagetest-api#25]
Installed the webpagetest cli and executed test and it throws an error Missing API key

```
 webpagetest test http://twitter.com/marcelduran
{
  "statusCode": 400,
  "statusText": "An error occurred processing your request.  Please reload the testing page and try submitting your test request again. (missing API key)"
}%
```

**Comment by badrinathvm** [comment]
Hi , How can i get API Key to test Web Page from sitespeed.io , i requested API key from below http://www.webpagetest.org/getkey.php , after performing tests i am facing below exception 
![screen shot 2015-02-20 at 11 04 40 am](https://cloud.githubusercontent.com/assets/1479179/6307719/0ad4a5c0-b8f3-11e4-92a8-a53275ad3011.png)

Any help is appreciated

**Comment by pmeenan** [comment]
You will have to check with sitespeed.io for how to configure the API key.  From the looks of the log and the message your API key is not being sent to WebPageTest from your sitespeed.io instance.

**Comment by hatzopoulos** [comment]
> How can i get API Key to test Web Page from sitespeed.io , i requested API key from below http://www.webpagetest.org/getkey.php , after performing tests i am facing below exception

From the "[A little more nerdy][1]" section of the sitespeed.io documentation
`sitespeed.io -u http://example.com  --wptHost www.webpagetest.org --wptKey MY_SECRET_API_KEY`

[1]: https://www.sitespeed.io/documentation/configuration/#a-little-more-nerdy
