### ISSUE TITLE
wpt.runTest () is timing out

### ISSUE THREAD

**Issue by bousquetcm** [marcelduran/webpagetest-api#32]
Result:
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'co
nnect' }

Running:
var wpt = new WebPageTest('www.webpagetest.org', '[my key here]');
wpt.runTest('www.twitter.com', function callback(err, data) {
  console.log(err || data);
});

Not sure what's up, but getting nothing but timeout. Its a windows machine running Node.

**Comment by JeroenVdb** [comment]
@bousquetcm I'm also getting this timeout error from time to time (runTest fails 30% of the time). Can you elaborate about your solution?
