### ISSUE TITLE
Invalid locations

### ISSUE THREAD

**Issue by deanet** [marcelduran/webpagetest-api#36]
Hello..

Trying to test your webpagetest-api but still not found location:

webpagetest test http://www.obat24.com --key A.1231231 --location Singapore_IE8
{
  "statusCode": 400,
  "statusText": "Invalid Location, please try submitting your test request again."

any advices ?

**Comment by namnn96** [comment]
Hi @pmeenan,

I got this error while running sitespeedio. The fact that I tried all Dulles:Chrome as well as Dulles:Firefox and neither works. ec2-us-west-2:Firefox as you can see doesn't work. Is there any location that is still valid?

Running WebPageTest **** pollResults=10, timeout=600, firstViewOnly=false, runs=n, private=true, aftRenderingTime=true, location=ec2-us-west-2:Firefox, connectivity=Cable, video=true
error: WebPageTest couldn't fetch info for url http://internetrix.com.au{ statusCode: 400,
  statusText: 'Invalid Location, please try submitting your test request again.' }
error: Error running WebPageTest: { statusCode: 400,
  statusText: 'Invalid Location, please try submitting your test request again.' }


Thanks in advance.

**Comment by pmeenan** [comment]
@namnn96 - you should probably email me directly with the details of the config.  i.e. are you pointing to www.webpagetest.org or to a private instance?  Have you tried just with the command line to narrow it down?

I can guarantee that the locations are up and running and accepting tests on the public instance so it's something else in your config.

**Comment by fakusan** [comment]
Hi @pmeenan 

Appreciated if you could help that how to use Tokyo, Japan (KDDI LTE).
It's available on http://www.webpagetest.org/getLocations.php?f=html&k=, but not available on http://www.webpagetest.org/getLocations.php?f=html&k=A .
When I choose Tokyo_Headspin through API, I see this message, "{u'statusText': u'Invalid Location, please try submitting your test request again.', u'statusCode': 400}".

Thank you for your help in advance.

Best Regards,

**Comment by fakusan** [comment]
Hi @pmeenan 

Appreciated if you could help that how to use Tokyo, Japan (KDDI LTE).
It's available on http://www.webpagetest.org/getLocations.php?f=html&k=, but not available on http://www.webpagetest.org/getLocations.php?f=html&k=A .
When I choose Tokyo_Headspin through API, I see this message, "{u'statusText': u'Invalid Location, please try submitting your test request again.', u'statusCode': 400}".

Thank you for your help in advance.

Best Regards,

**Comment by pmeenan** [comment]
@fakusan - The mobile network locations are not available through the API.  Testing from Tokyo through the API needs to be done through the EC2 instances in ap-northeast-1 location.

If you need API testing from a headspin location and are interested in their commercial testing services I can put you in contact with them.

**Comment by fakusan** [comment]
@pmeenan 
Thank you for your reply!
I tried ap-northeast-1 with below. So this line is down speed with almost 5Mbps (5000 bytes) and up speed 1Mbps, correct?
Is it possible to set faster one in Tokyo? e.g. location=Tokyo.custom&bwDown=10240&bwUp=2048&latency=28&plr=0 etc. I saw Location.custom is also available, but Tokyo.custom got an error.

Thank you for your help.

"location":"ec2-ap-northeast-1:Chrome","from":"Japan - EC2 - <b>Chrome<\/b> - <b>Cable<\/b>","connectivity":"Cable","bwDown":5000,"bwUp":1000,"latency":28,"plr":"0","mobile":1

**Comment by pmeenan** [comment]
Custom connectivity for the Tokyo EC2 location would look like this:

location=ap-northeast-1:Chrome.custom&bwDown=10240&bwUp=2048&latency=28

**Comment by fakusan** [comment]
It works! Thank you for your help!

**Comment by namnn96** [comment]
Hi @pmeenan,

My instance is located in oregon and i think location us-west-2:Chrome should work. However, I always receive invalid location. Also when I go to <my_instance_ip>/getLocations.php there is no idle tester, everything is 0.

Is this something wrong with my instance configuration or there is actually nothing at west us instances?

Thank you

**Comment by pmeenan** [comment]
With the EC2 server image the AMI's are configure to start on demand so there will not be any idle testers until the first test is submitted.  If you are getting invalid location then the ID you are passing the API doesn't match what is in getLocations.php

**Comment by namnn96** [comment]
I get the API from http://www.webpagetest.org/getkey.php and use it for every instance I create but none of them works. Is it because this API only works for public http://www.webpagetest.org/ and not for ec2 instances?

Thanks.

**Comment by pmeenan** [comment]
Those keys are only for the public instance.  If you are running a private instance then you manage your own keys.

If you are using the server AMI then you can either provide a user data string that includes an API key for clients when it is first created or if you don't one will be generated automatically and you will have to log into the server directly (ssh) to see what it is (or configure more).

The keys are configured in /var/www/webpagetest/www/settings/keys.ini

**Comment by namnn96** [comment]
Thanks @pmeenan, I found the api key and after replacing it with the public key, things work as charm.

**Comment by sachinbanugariya** [comment]
If you are running a private instance then you manage your own keys.

ok how can i generate my own key for private instance for command line.

and can you please example how will be i make api key and how will be the command.

thanks.

**Comment by pmeenan** [comment]
rename settings/keys.ini.sample to keys.ini on your server and populate any API keys you want to use.

**Comment by sachinbanugariya** [comment]
hello,
thanks for reply.
i added key which i got from WebPagetest API Key to keys.ini.
[server]
secret=AnyRandomSecretKeyOrHash
key=added_MY_KEY_here

but still seems same 
{
  "statusCode": 400,
  "statusText": "Invalid API Key"
}

anything else need to configure.
Thanks.

**Comment by pmeenan** [comment]
You don't need to use the keys you get from the public instance - they don't mean anything special.  The keys are just strings.  It looks like you added the key in the wrong place.  The server itself needs an API key for it's internal operation (lets say that key is 123456789) and let's say your API key is 998877 and you also have a second key for other testing that is 556677 (and has a limit of 500 tests per day), your keys.ini would look like:

```
[server]
secret=XXYYZZ
key=123456789

[123456789]
description=Web UI
contact=me@me.com
limit=0

[998877]
description=API Key
contact=me@me.com
limit=0

[556677]
description=Limited API Key
contact=me@me.com
limit=500
```

**Comment by sachinbanugariya** [comment]
ok thanks.
can you please send me example of webpage test command:
i used below command and add your above keys.ini
webpagetest test https://twitter.com/marcelduran --key 998877/123456789 --location Beijing --server server.xxxx.com
but still same issue,

need to specify --key parameter in command line ?
can you please send me command example with which key i need to specify in --key parameter for command test.

thanks

**Comment by pmeenan** [comment]
The 998877 key is what you should specify on the command-line.

**Comment by pmeenan** [comment]
For server you may need to specify http://server.xxxx.com (assuming your server is there).

To test the WebPageTest install itself to make sure it is working before focusing on the command-line you can load the runtest URL in the browser and see if it runs your test:

```
http://server.xxxx.com/runtest.php?k=998877&location=Beijing&url=www.google.com
```

**Comment by sachinbanugariya** [comment]
yes. already installed private instance,
the thing is that on URL it is working before when i configured and not use keys.ini that time and use public api key settings location.ini file added.
but from command line not able to got results when i use --server parameter only,
if use without --server parameter it will works fine without any issue but results cames from webpagetest.xxxx.com.
but we want results from our private server like myserver.com/result.

so once i use webpagetest command with --server option with my server name where my private instance is running also not gives results and gives location issue, key issue like that.


after filled settings as given by you now on URL test it also gives invalid key error.

thanks.

**Comment by pmeenan** [comment]
If your private instance was working without keys.ini but not on the command-line, you should remove keys.ini and get the command-line working first.  My guess is that the server parameter is not being passed correctly.

If the url I gave you is not working correctly, assuming you have the correct server in the url, then the keys.ini isn't configured like the example I gave you or it isn't in the correct location or the file permissions are such that the user running the web server account can't read it.

**Comment by sachinbanugariya** [comment]
ok right now the thing is both side running webpagetest (using web url and also from command line),
now what i need to do for result seems from:

but still not work below thing:
http://xxx.server.com/runtest.php?k=A.XXXXX9f4e9b0XXXX9b1b1954098eed&location=Beijing&url=www.google.com

and also not work command line:
webpagetest test https://facebook.com --key A.cb529269f4e9b036219b1b1954098eed --location ec2-us-east-1:Chrome --server tahoe.shangyeguwen.com

working things:
1. webpagetest test https://facebook.com --key A.cb529269f4e9b036219b1b1954098eed --location ec2-us-east-1:Chrome
2. working also from web url normal test.

but issue is that result is came from www.webpagetest.orgXXXX how can i got results from my private instance which is myserver.com/XXXXX.


thanks.

**Comment by UJUDURU1** [comment]
How do I get Dulles:Chrome location to work? as I have been getting this error:
{
"statusCode": 400,
"statusText": "Invalid Location, please try submitting your test request again."

**Comment by MixmasterRick** [comment]
> How do I get Dulles:Chrome location to work? as I have been getting this error: { "statusCode": 400, "statusText": "Invalid Location, please try submitting your test request again."

Did you ever find a solution to this? I have the same status code (which seems to indicate an invalid API), trying to figure it out but no luck yet.

**Comment by pmeenan** [comment]
@MixmasterRick are you using a private instance or the Catchpoint WebPageTest?  If you're using Catchpoint, the locations list is [here](https://www.webpagetest.org/getLocations.php?f=html) (Dulles is no longer one of them).

i.e. ec2-us-east-1:Chrome should work for Virginia-based testing with Chrome.

**Comment by MixmasterRick** [comment]
Hi Patrick -

I had attempted to use ec2-us-east-1:Chrome just as you said. I'm
attempting to use the WPT Bulk Tester google sheet I assume you're familiar
with. It's giving me a 400 status suggesting there is an API issue.

**Comment by MixmasterRick** [comment]
Hi Patrick - thought I'd check in. With it seemingly not a location issue,
any other thoughts as to what the issue might be?

**Comment by pmeenan** [comment]
Are you using a purchased API key from www.webpagetest.org? If so, does it work to run a test on the command-line? There are a LOT of users using the commercial keys so if there is an underlying problem I'd expect everything would be on fire.

If you run the cli with `--dryrun` it should give you the URL it is trying to use (which can then be debugged on its own).

**Comment by pmeenan** [comment]
Yep, sorry - pro + generate key should be all you need to do.  This github repository is for a command-line API that can use the API, not necessarily the bulk tester.  You might try pinging [Andy Davies](https://twitter.com/andydavies) on twitter who created the original bulk tester spreadsheet.

If you want to check to make sure your API key is working, you should be able to load the URL below into a browser and see if it triggers a test (substitute your actual API key for ApiKeyHere).  That will narrow down the problem to be with the key itself or with the bulk tester.

```
https://www.webpagetest.org/runtest.php?fvonly=1&url=https%3A%2F%2Fwww.webpagetest.org%2F&k=ApiKeyHere
```

**Comment by MixmasterRick** [comment]
Hi Patrick -

Thanks so much. Sorry, didn't realize I had strayed off of the beaten path
so far.

The test URL worked with my API key, so there's either an issue with the
spreadsheet, or more likely, my implementation of it somehow. Will explore
a bit further. Appreciate your help.

Rick

**Comment by MixmasterRick** [comment]
Hi again Patrick -

Sorry to continue to bug with my non-technical questions, but I still can't
quite figure out why it's not working. My API key tests as valid. Could the
issue be the URL? I'm using https://www.webpagetest.org in the spreadsheet
URL field, but since I'm using a private API key, should I be using a
different URL?

**Comment by pmeenan** [comment]
No, that URL should be fine and matches the test URL above.
