### ISSUE TITLE
Invalid Location

### ISSUE THREAD

**Issue by fracklen** [marcelduran/webpagetest-api#49]
With a brand new API-key, I can't get any of the locations to work.

I'm located in Denmark, so using e. g. Copenhagen:Chrome would seem like an obvious choice

```bash
$ webpagetest test --key $API_KEY --location "Copenhagen:Chrome.DSL" --poll --runs 3 -p https://www.example.dk                                                       [15:38:11]
{
  "error": {
    "statusCode": 400,
    "statusText": "Invalid Location, please try submitting your test request again."
  }
}
$ webpagetest test --key $API_KEY --location "Copenhagen:Chrome.Cable" --poll --runs 3 -p https://www.example.dk                                                     [15:38:17]
{
  "error": {
    "statusCode": 400,
    "statusText": "Invalid Location, please try submitting your test request again."
  }
}
$ webpagetest test --key $API_KEY --location "Copenhagen" --poll --runs 3 -p https://www.example.dk                                                                  [15:38:32]
{
  "error": {
    "statusCode": 400,
    "statusText": "Invalid Location, please try submitting your test request again."
  }
}
```

I've tried with quite a lot of the location ids found in the `webpagetest locations` - No luck.

If I don't specify a location, I get the default Dulles, and the test runs just fine.

Help? - What am I doing wrong?

**Comment by fracklen** [comment]
Nevermind - I just found the forum, where they tell which locations are available for the Akamai sponsored api-keys.

For future reference: http://www.webpagetest.org/forums/showthread.php?tid=13743

**Comment by pmeenan** [comment]
FWIW, all of that information should have also have been in the email with the API key.
