### ISSUE TITLE
Support 2G in connectivity

### ISSUE THREAD

**Issue by jdlrobson** [marcelduran/webpagetest-api#53]
Hi there! I work at @wikimedia and we're using this and it's great! We are currently trying to improve things for our 2G users and this library doesn't support it.

Also how actively is this extension being worked on? Wikimedia would be interesting in helping maintaining it if that is useful. cc @soulgalore

**Comment by marcelduran** [comment]
`--connectivity` parameter has no validation it's just an info [listing the possible list of connectivity support](https://github.com/marcelduran/webpagetest-api/blob/master/lib/mapping.js#L40).
That being said, you can safely run your tests putting pretty much any string as connectivity, in your case, 2G or 2GFast. E.g.:
```console
$ webpagetest test http://example.com --connectivity=2G
```
Or via Node.JS:
```javascript
var wpt = require('webpagetest')('http://my-private-wpt.com');
wpt.runTest('http://example.com', {connectivity: '2G'}, function(err, data) {
  console.log(err || data);
});
```
I'll update the list of current supported connectivities (per webpagetest.org) soon.

**Comment by bigethan** [comment]
The code that deals with connectivity does indeed have validation, it has to pass this regex: `/^(?:Cable|DSL|FIOS|Dial|3G|3GFast|Native|custom)$/,` per https://github.com/marcelduran/webpagetest-api/search?utf8=%E2%9C%93&q=reConnectivity&type=Code
