### ISSUE TITLE
2nd test run with same options object

### ISSUE THREAD

**Issue by furybyname** [marcelduran/webpagetest-api#55]
Using the following code:

```
var WebPageTest = require('webpagetest');

var wpt = new WebPageTest('server', 'key');

var options = {
    pollResults: 5,
    timeout: 60
}

function runTest(url) {
    wpt.runTest(url, options, function(err, data) {
        runTest('some-other-url');
    });
}

runTest('some-url');
```

The options object has been modified after the first test run is complete, meaning for the 2nd run the following is passed:

```
{
 pollResults: 5000,
 timeout: 60000
}
```

This is because of:

```
options.timeout = (parseInt(options.timeout, 10) || 0) * 1000;
and 
options.pollResults = parseInt(options.pollResults * 1000, 10) || 5000;

```

This can be worked around by passing a new object each time but using the same object is fairly common. It would be better if the options object was not modified.

Use-case is here is gathering data from multiple urls with a single script.

**Comment by furybyname** [comment]
Would it be better to clone the whole object, or just created new variables for those modified ones?Cloning would future-proof it a bit more I think.

**Comment by tkadlec** [comment]
Hit this today myself.

Cloning the object seems like a good future-forward way of handling this. I'll try to hit this tomorrow.
