### ISSUE TITLE
HTTP authentication not working

### ISSUE THREAD

**Issue by callumacrae** [marcelduran/webpagetest-api#57]
Hello!

I'm running a private instance of webpagetest behind HTTP auth. It works through the browser. However, if I enter the same stuff in the command line:

```
$ webpagetest test https://www.lostmy.name/ --server http://local-wpt/ -g user -w pass
```

It doesn't work:

```
{
  "error": {
    "name": "WPTAPIError",
    "code": 401,
    "message": "Unauthorized"
  }
}
```

Any ideas? Is this a problem with the module, or with how I'm using it?

**Comment by pmeenan** [comment]
I'm pretty sure the -g and -w options are for passing credentials to WebPageTest to use when testing sites, not for authenticating to the server itself.

Have you tried --server http://user:pass@local-wpt/ ?  Passing the credentials as part of the URL may work (not sure if Node honors that or not).

**Comment by callumacrae** [comment]
Throws a 401 again.

> -g, --login <username>: username for authenticating tests (http authentication)
> -w, --password <password>: password for authenticating tests (http authentication)

It does specify http authentication!

**Comment by pmeenan** [comment]
Yes - http authentication for the test itself (Auth tab in the advanced setting of the webpagetest UI), not for the API to access the server.  Marcel will have to weigh-in if it's possible to use auth on the API itself or if it will require changes.

**Comment by callumacrae** [comment]
Ah I see! If it does require changes, I'm fine to make them—I'm guessing it won't be that tricky.

**Comment by callumacrae** [comment]
@marcelduran Is this library still maintained?

**Comment by marcelduran** [comment]
Hi @callumacrae, sorry for the delay. Yes this lib is still maintained, however I've been quite busy lately. Would you mind looking into [`normalizeServer`](https://github.com/marcelduran/webpagetest-api/blob/master/lib/helper.js#L174) and apply the changes to support credentials (with [tests](https://github.com/marcelduran/webpagetest-api/blob/master/test/edge-cases-test.js#L142) please)? I'll be more than happy to merge a PR.
Thanks,

**Comment by callumacrae** [comment]
On it.

Tests are failing on a clean branch, though:

```
  1) Example WebPageTest for Specs Hits a Nock Server gets a sync test with results with perf test specs request then waits for test results object:
     Uncaught AssertionError: { [Error: Nock: No match for request GET http://foobar10.com/runtest.php?url=http%3A%2F%2Ftwitter.com%2Fmarcelduran&runs=3&fvonl == 0
      at test/specs-test.js:38:16
      at WebPageTest.testCallback (lib/webpagetest.js:350:14)
      at callbackYield (lib/webpagetest.js:138:14)
      at WebPageTest.apiCallback (lib/webpagetest.js:207:7)
      at OverriddenClientRequest.onError (lib/webpagetest.js:131:5)
      at node_modules/nock/lib/request_overrider.js:208:11

  2) Example WebPageTest for Sync Hits a Nock Server gets a sync test with results with custom median metric request then waits for test results object:
     Error: Nock: No match for request GET http://foobar2.com/runtest.php?url=http%3A%2F%2Ftwitter.com%2Fmarcelduran&runs=3&fvonly=1&medianMetric=TTFB&f=json&pingback=http%3A%2F%2F127.0.0.1%3A8001%2Ftestdone
      at RequestOverrider.end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:167:7)
      at Object.exports.get (http.js:36:7)
      at WebPageTest.get (lib/webpagetest.js:80:19)
      at WebPageTest.api (lib/webpagetest.js:177:9)
      at WebPageTest.listener (lib/webpagetest.js:386:9)
      at emitListeningNT (net.js:1260:10)
```
