### ISSUE TITLE
How to Set Cookie value in scriptToString ?

### ISSUE THREAD

**Issue by badrinathvm** [marcelduran/webpagetest-api#63]
How to Set Cookie value in scriptToString ?

Hello,

Unable to set cookie value in scriptToString method , below is my syntax , Can you guys please validate and let me know the fix ?

script = wpt.scriptToString([
{navigate: http://www.xyz.com},
{setViewportSize: [1280,1024]},
{setCookie: [ http://www.xyz.com, 'SEGMENT=%7B%22EXPERIMENT%22%3A%5B1063%5D%7D']} ]);

**Comment by marcelduran** [comment]
Missing quotes?
```javascript
script = wpt.scriptToString([
  {navigate: 'http://www.xyz.com'},
  {setViewportSize: [1280,1024]},
  {setCookie: [ 'http://www.xyz.com', 'SEGMENT=%7B%22EXPERIMENT%22%3A%5B1063%5D%7D']}
]);
```
