### ISSUE TITLE
Error 400 when I try to create a compare video

### ISSUE THREAD

**Issue by andre487** [marcelduran/webpagetest-api#70]
```
➜  webpagetest video 160113_1J_Z4F,160113_1P_Z4G
{
  "statusCode": 400,
  "statusText": "Error creating video"
}
```

**Comment by pmeenan** [comment]
Not sure if it is the cause of the 400 in the API but it doesn't look like either of those tests were run with video capture enabled so you won't be able to create video from them.

**Comment by andre487** [comment]
Yes, it's right. Thanks for the help!
