### ISSUE TITLE
Error 301 - Moved Permanently 

### ISSUE THREAD

**Issue by Qassim** [marcelduran/webpagetest-api#77]
Hi,

Upon running tests, it has recently begun returning the following:

`{
  "error": {
    "name": "WPTAPIError",
    "code": 301,
    "message": "Moved Permanently"
  }
}
`

I believe it may be due to webpagetest removing support for http on their API and redirecting to https, but the build in method for GET requests doesn't follow such redirects.

**Comment by Qassim** [comment]
Attempted a quick fix, but realised it wasn't as simple as I expected (although it does for my case, the tests fail) - don't have time to look into it just yet, so closed it for now.

**Comment by pmeenan** [comment]
Until the default gets switched you can work around it by specifying --server=https://www.webpagetest.org/

**Comment by jpswade** [comment]
Passing in the server works OK for runTest, but I also needed to pass in the parameters to the getTestStatus and getTestResults functions.

**Comment by vasikarla** [comment]
@pmeenan @jpswade : could you kindly let me know where exactly do i need to change the server details?

**Comment by soulgalore** [comment]
@vasikarla depending on how you run it. If you embed the API, change the URL:
<pre>
var wpt = new WebPageTest('https://www.webpagetest.org');
</pre>

Or if you run it in the command line, do as Pat suggested, add <code>--server=https://www.webpagetest.org/</code>
