### ISSUE TITLE
SpeedIndex attribute not supported.

### ISSUE THREAD

**Issue by jenssvensson** [marcelduran/webpagetest-api#88]
Is there any way to get the SpeedIndex attribute in the response using the command line interface? 

Something like this: 
`webpagetest test http://staging.example.com --first --server http://<some private instance>/ --connectivity 3G --location us_east_wptdriver --poll 5 --timeout 60 > staging.json
`

**Comment by soulgalore** [comment]
Hey @jenssvensson you need to turn on video and you will get SpeedIndex in your result.
