### ISSUE TITLE
Question : why mocha is dependency over a devdependency ?

### ISSUE THREAD

**Issue by abarre** [marcelduran/webpagetest-api#92]
I see that the module install mocha when it is imported. I think that this is a mistake in the package file.
mocha should be a dev dependency, isn't it ?

**Comment by marcelduran** [comment]
No, mocha is used to generate the report output for WPT tests using specs besides the regular project unit tests. I understand the confusion. Perhaps should add some [comments on the package.json](https://groups.google.com/forum/#!msg/nodejs/NmL7jdeuw0M/yTqI05DRQrIJ).
